version: '3'
services:
  frontend:
    container_name: app-frontend
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend
  backend:
    container_name: app_backend
    build: ./backend
    tty: true
    command: sh
    working_dir: /app-backend
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - db
    platform: linux/x86_64
  db:
    container_name: db
    ports:
      - 3306:3306
    image: mysql:8.0.32
    env_file:
      - .env
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
